/* 护生之约 · strings.js
 * All words in the game, in Chinese (zh) and English (en).
 * Poems and inscriptions are quoted in Chinese in both languages; the English
 * side adds a translation under the key ending in "En".
 * A key missing from `en` falls back to `zh`. */
window.STR = {};

STR.zh = {
  /* app */
  'app.name': '护生之约',
  'app.sub': '走进丰子恺的《护生画集》',
  'app.lede': '一本空白的画册，六个小生命，一个守了四十多年的约定。',
  'app.credit': '游戏中的插图是仿丰子恺笔意的原创绘画，不是原作。',

  /* title screen */
  'title.start': '翻开画册',
  'title.continue': '继续画我的画册',
  'title.teacher': '给老师',
  'title.nameLabel': '在画册封面写下你的名字',
  'title.namePh': '你的名字（可以不填）',
  'title.nameHint': '名字会刻成一枚红色印章，盖在你的画上。',

  /* shared ui */
  'ui.album': '画册',
  'ui.cover': '封面',
  'ui.backToAlbum': '回到画册',
  'ui.sound': '声音',
  'ui.soundOn': '声音已打开',
  'ui.soundOff': '声音已关闭',
  'ui.lang': 'English',
  'ui.langName': '中文',
  'ui.next': '下一页',
  'ui.prev': '上一页',
  'ui.start': '开始',
  'ui.continue': '继续',
  'ui.ok': '好的',
  'ui.toPage': '翻到画页',
  'ui.collect': '收入画册',
  'ui.again': '再玩一次',
  'ui.close': '关闭',
  'ui.seals': '慈心印',
  'ui.sealsN': '{n} 枚慈心印',
  'ui.pageN': '第{n}页',
  'ui.pov': '倘使我是它',
  'ui.talk': '想一想，说一说',
  'ui.know': '你知道吗',
  'ui.fromBook': '画集里的故事',
  'ui.today': '今天的护生',
  'ui.save': '保存图片',
  'ui.saving': '正在准备图片……',
  'ui.saved': '图片已保存。',
  'ui.saveDeclined': '没有保存。想保存时再点一次。',
  'ui.saveManual': '在图片上按右键（手机上长按）就可以保存。',
  'ui.catTap': '点一点白象，听它讲个小故事',
  'ui.catName': '白象',
  'ui.meow': '喵～',
  'ui.easyOn': '慢速模式已打开',
  'ui.loading': '正在展开画卷……',
  'ui.close2': '收起',
  'ui.rotate': '把手机横过来，画面会更大。',

  /* cat's little stories */
  'cat.facts': [
    '丰子恺的老家在浙江桐乡的石门湾，那里有河，有桥，有很多杨柳。',
    '丰子恺的家叫“缘缘堂”。名字是在弘一法师的建议下抓阄得来的：抓了两次，都是“缘”字！',
    '“漫画”这个词，是从“子恺漫画”开始在中国流行起来的。',
    '丰子恺特别喜欢孩子，很多画画的就是他自己的孩子。',
    '丰子恺画人，常常不画眼睛、鼻子和嘴巴。你猜为什么？',
    '李叔同写的《送别》，你会唱吗？“长亭外，古道边，芳草碧连天……”',
    '我最喜欢在太阳底下睡午觉。喵～',
    '倘使我是它——每次遇到小生命，都可以这样问问自己。',
  ],

  /* original paintings */
  'orig.real': '丰子恺原画',
  'orig.sketch': '示意图 · 原画扫描待添加',
  'orig.by': '丰子恺画',
  'orig.heading': '丰子恺的原画',
  'orig.unlocked': '这一页为你打开了一幅丰子恺的原画',
  'leaf.verseCard': '这一页的诗句',

  /* album */
  'album.title': '我的护生画册',
  'album.titleNamed': '{name}的护生画册',
  'album.progress': '已画 {done}/6 页 · {seals} 枚慈心印',
  'album.todo': '还没画',
  'album.done': '画好了',
  'album.read': '已读',
  'album.finish': '六页都画好了！丰子恺守住了和老师的约定，你也画完了自己的画册。',
  'album.prologue': '序 · 一个约定',
  'album.prologueDesc': '丰子恺和老师的约定',
  'album.studio': '末页 · 我的护生画',
  'album.studioDesc': '画一幅自己的护生画，题上诗，盖上印章。',
  'album.quiz': '护生小博士',
  'album.quizDesc': '答对问题，领取“护生小画师”证书。',
  'album.quizPassed': '已获得证书',
  'album.hint': '可以按顺序画，也可以先挑喜欢的一页。',

  /* prologue */
  'pro.title': '一个约定',
  'pro.p1.t': '学画的少年',
  'pro.p1': '一百多年前，在杭州的浙江省立第一师范学校，有个学生叫丰子恺。他跟着李叔同老师学画画、学音乐。李叔同多才多艺，还写过一首至今传唱的歌——《送别》：“长亭外，古道边，芳草碧连天……”',
  'pro.p2.t': '老师出家了',
  'pro.p2': '1918年，李叔同在杭州出家，成了弘一法师。他放下了许多爱好，只留下书法。可是，师生之间的情谊一直没有断。',
  'pro.p3.t': '五十幅画，一份寿礼',
  'pro.p3': '1929年，老师五十岁。丰子恺画了五十幅画作为寿礼，老师为每一幅配上诗句，亲笔写下。这些画说的都是同一件事：爱护一切生命。这就是《护生画集》第一集。',
  'pro.p4.t': '一个约定',
  'pro.p4': '十年后，老师六十岁，丰子恺又画了六十幅。老师来信，希望他在自己七十岁时画七十幅，八十岁时画八十幅，九十岁时画九十幅，一百岁时画一百幅。丰子恺回信说：',
  'pro.p4.quote': '世寿所许，定当遵嘱。',
  'pro.p4.gloss': '意思是：只要我还活着，一定照您说的做。',
  'pro.p5.t': '约定还在',
  'pro.p5': '1942年，弘一法师去世了。可是约定还在。在战乱和艰难的岁月里，丰子恺一集一集地画下去：七十幅，八十幅，九十幅……',
  'pro.p6.t': '四百五十幅',
  'pro.p6': '1973年，丰子恺悄悄画完了最后的一百幅。六集，一共四百五十幅，他用了四十多年，守住了对老师的承诺。点一点书架上的画集，看看每一集的故事。',
  'pro.p7.t': '现在，轮到你了',
  'pro.p7': '丰子恺说：“护生者，护心也。”爱护小生命，也是在守护我们自己那颗善良的心。现在，这本空白的画册交给你了。',
  'pro.p7.cat': '喵～我叫白象。丰子恺家从前有一只白猫就叫这个名字，他还为它写过一篇文章呢。让我陪你一页一页画下去吧！',
  'pro.open': '打开我的画册',
  'pro.shelfHint': '点一本画集',
  'pro.vol': [
    { n: '第一集', year: '1929', count: '50幅', by: '弘一法师配诗、书写', note: '为老师五十岁祝寿' },
    { n: '第二集', year: '1940', count: '60幅', by: '弘一法师书写', note: '为老师六十岁祝寿' },
    { n: '第三集', year: '1949', count: '70幅', by: '叶恭绰书写', note: '老师已经去世，约定还在' },
    { n: '第四集', year: '1960', count: '80幅', by: '朱幼兰书写', note: '' },
    { n: '第五集', year: '1965', count: '90幅', by: '虞愚书写', note: '' },
    { n: '第六集', year: '1973', count: '100幅', by: '朱幼兰书写', note: '在艰难的年代悄悄画完，1979年出版' },
  ],

  /* chapter frame */
  'ch.intro': '这一页的故事',
  'ch.howto': '怎么玩',
  'ch.skipIntro': '直接开始',
  'ch.done': '这一页画好了！',
  'ch.sealsGot': '你得到了 {n} 枚慈心印',
  'ch.sealWhy3': '你是那么细心，小生命都平平安安。',
  'ch.sealWhy2': '做得不错！下次还可以更轻、更慢一点。',
  'ch.sealWhy1': '画好了！再玩一次，试试更小心一点。',
  'ch.replay': '重玩这一页',

  /* 1 · ants */
  'ants.title': '扫地',
  'ants.animal': '蚂蚁',
  'ants.season': '春',
  'ants.intro': '春天，院子里落满了柳叶。拿起扫帚扫扫地吧！不过，请先低头看一看——地上有一队小客人正在赶路。',
  'ants.howto': '按住并拖动扫帚，把落叶扫走；也可以点一下落叶，把它轻轻捡起来。别碰到蚂蚁，慢一点没关系。',
  'ants.stat': '落叶 {a}/{b} · 惊扰 {c}',
  'ants.oops': '哎呀，吓到它了！',
  'ants.poke': '嘘——它正忙着回家呢。',
  'ants.rain': '蚂蚁在搬家……看样子要下雨了，它们得赶快回家。',
  'ants.gentle': '轻轻的，真好。',
  'ants.win': '扫干净啦！小蚂蚁们也平平安安到家了。',
  'ants.povTitle': '倘使我是一只蚂蚁',
  'ants.pov': '倘使你是一只蚂蚁，一把扫帚落下来，就像整片竹林从天上压下来。你背着一粒饭，只想快点回家。',
  'ants.ask': '你在哪里见过蚂蚁？下次遇见它们，你会怎么做？',
  'ants.verse': '扫地恐伤蝼蚁命',
  'ants.verseBy': '古语',
  'ants.verseGloss': '扫地的时候，怕伤了蚂蚁的性命。',
  'ants.know': '一窝蚂蚁可以有成千上万只，它们分工合作：有的找食物，有的照顾宝宝。下雨前空气变得潮湿，蚂蚁常常忙着搬家，所以民间有“蚂蚁搬家，天要下雨”的说法。',
  'ants.book': '《护生画集》里画了许多这样的小生命：蚂蚁、蝴蝶、青蛙、小鸟……在丰子恺眼里，它们和我们一样，都有自己的家。',

  /* 2 · pond */
  'pond.title': '清池',
  'pond.animal': '鱼',
  'pond.season': '夏',
  'pond.intro': '夏天的池塘，本来是鱼儿的家。可是有人把垃圾丢进了水里，还有一条鱼被丢弃的渔线缠住了。',
  'pond.howto': '点一下水里的垃圾，用网兜捞上来。小心别网到鱼！看到被渔线缠住的鱼，点一下帮它解开。',
  'pond.stat': '垃圾 {a}/{b} · 解救 {c}/1 · 惊扰 {d}',
  'pond.oops': '鱼儿吓了一跳！',
  'pond.freed': '解开了！它又能自在地游了。',
  'pond.tangledHint': '那条鱼被渔线缠住了，点一下它！',
  'pond.win': '池水清了，鱼儿的家回来了。',
  'pond.povTitle': '倘使我是一条鱼',
  'pond.pov': '倘使你是一条鱼，一只塑料袋漂在头顶，就像一片永远不会散开的乌云。',
  'pond.ask': '你家附近有河流、池塘或者小溪吗？怎样才能让那里的生命过得好一点？',
  'pond.verse': '细雨鱼儿出，微风燕子斜。',
  'pond.verseBy': '杜甫《水槛遣心》',
  'pond.verseGloss': '细细的雨里，鱼儿游上水面；微微的风中，燕子斜着身子飞。',
  'pond.know': '有人会买鱼来“放生”。可是随便把外地的鱼放进河里，可能会伤害原来住在那里的生命。守护生命最好的办法，是守护它们本来的家——让水保持干净。',
  'pond.book': '丰子恺的时代，水里还没有这么多塑料。今天我们说“护生”，也包括守护河流、森林和天空。',

  /* 3 · moths */
  'moth.title': '纱灯',
  'moth.animal': '飞蛾',
  'moth.season': '夏夜',
  'moth.intro': '夏天的夜晚，书桌上点着一盏油灯。窗外飞进来几只飞蛾，一只接一只朝火苗飞去……',
  'moth.howto': '点一下飞蛾，引它从窗口飞回月光里。别让它碰到火苗！',
  'moth.stat': '飞回月光里 {a} · 烫伤 {b}',
  'moth.hot': '太烫了！',
  'moth.saved': '去吧，月光在那边。',
  'moth.gauzeCue': '白象找来了一个纱罩！把它拖到油灯上罩住。',
  'moth.gauzeOn': '罩上纱罩，灯照样亮，飞蛾却不会被烫伤了。',
  'moth.moonAsk': '今晚的月亮真亮。要不要吹灭油灯，一起看月亮？',
  'moth.blow': '吹灭油灯',
  'moth.win': '灯灭了，飞蛾们都飞向了月光。',
  'moth.povTitle': '倘使我是一只飞蛾',
  'moth.pov': '倘使你是一只飞蛾，那团火光就像一个让你分不清上下的谜，你只能绕着它，一圈又一圈。',
  'moth.ask': '纱罩是一个保护小生命的“小发明”。你还能想到哪些这样的好办法？',
  'moth.verse': '为鼠常留饭，怜蛾不点灯。',
  'moth.verseBy': '苏轼',
  'moth.verseGloss': '常常给老鼠留一点饭；可怜飞蛾，夜里就不点灯。',
  'moth.know': '飞蛾为什么绕着灯飞？科学家发现，飞虫会把背朝向最亮的地方，用来分清上和下。灯光让它们迷失了方向，只好绕着灯打转。所以，晚上不用的灯，记得关掉。',
  'moth.book': '还记得第一页的“扫地恐伤蝼蚁命”吗？它的下一句是“爱惜飞蛾纱罩灯”——给灯罩上纱罩，是为了爱惜飞蛾。',

  /* 4 · nest */
  'nest.title': '望母归',
  'nest.animal': '雏鸟',
  'nest.season': '秋',
  'nest.intro': '秋天的大树上有个鸟窝。鸟妈妈飞出去找虫子了，小鸟们正在等她回来。树下，一个男孩举起了弹弓……',
  'nest.boy1': '看我把枝头那只鸟打下来！',
  'nest.ask': '你想怎么劝他？',
  'nest.opt1': '不许打！我去告诉老师！',
  'nest.res1': '哼，老师又不在这儿。',
  'nest.hint1': '吓唬他，他只会躲着打。换个说法试试？',
  'nest.opt2': '嘘——你听，树上有小鸟在叫。它们在等妈妈回家呢。',
  'nest.res2': '……那只鸟，是它们的妈妈？',
  'nest.opt3': '打鸟有什么好玩的，我们去踢球吧！',
  'nest.res3': '可我就想打鸟嘛。',
  'nest.hint3': '换个游戏，他明天还会再来。要让他自己明白才行。',
  'nest.good': '他放下了弹弓。白居易有一首诗，说的正是这件事：',
  'nest.poem': '谁道群生性命微？一般骨肉一般皮。劝君莫打枝头鸟，子在巢中望母归。',
  'nest.poemBy': '白居易《鸟》',
  'nest.poemGloss': '谁说小动物的生命微不足道？它们和我们一样有血有肉。劝你别打树枝上的鸟，它的孩子正在窝里盼着妈妈回来。',
  'nest.wind': '忽然刮来一阵大风！一只小鸟从窝里掉了下来。',
  'nest.boy2': '我们一起把它送回去吧！',
  'nest.howto': '按住小鸟，慢慢把它送回窝里。太快了它会害怕，碰到树枝它会疼。',
  'nest.stat': '害怕 {a} · 碰撞 {b}',
  'nest.fearLabel': '小鸟害怕吗？',
  'nest.fast': '慢一点……它在发抖。停一停，等它安静下来。',
  'nest.calm': '好了，它不怕了。',
  'nest.bump': '小心树枝！',
  'nest.win': '鸟妈妈回来了！一家人又在一起了。',
  'nest.povTitle': '倘使我是一只小鸟',
  'nest.pov': '倘使你是一只刚掉出窝的小鸟，地面又大又冷，妈妈不知道在哪里。你只能一声一声地叫。',
  'nest.ask2': '想让别人不去做一件伤害生命的事，怎样说最有用？为什么？',
  'nest.verse': '劝君莫打枝头鸟，子在巢中望母归。',
  'nest.verseBy': '白居易《鸟》',
  'nest.verseGloss': '劝你别打树枝上的鸟，它的孩子正在窝里盼着妈妈回来。',
  'nest.know': '如果在地上看到一只羽毛差不多长齐、会蹦会跳的小鸟，它可能正在学飞，爸爸妈妈就在附近——最好远远看着，别打扰它。只有还没长好羽毛的雏鸟掉出窝，才需要轻轻送回去。另外，“人碰过的小鸟，鸟妈妈就不要了”只是一个误会。',
  'nest.book': '丰子恺画过许多鸟妈妈和孩子的画。在第六页“读画”里，你会看到其中很动人的一幅。',

  /* 5 · cage */
  'cage.title': '笼门',
  'cage.animal': '画眉',
  'cage.season': '冬',
  'cage.intro': '屋檐下挂着一只鸟笼，里面关着一只从山林里捉来的画眉。它每天都在笼子里“唱歌”……',
  'cage.intro2': '这一次，你就是笼子里的画眉。',
  'cage.howto': '点一下画面或按空格键扇动翅膀；点画面左边、右边，或按方向键，可以往左往右飞。',
  'cage.bump': '咚！',
  'cage.th1': '外面好大呀……',
  'cage.th2': '朋友们在叫我……',
  'cage.th3': '天空那么大，我却只有这么一点点。',
  'cage.outside': '现在，你回到了笼子外面。你想怎么做？',
  'cage.opt1': '多放些小米和清水',
  'cage.res1': '它吃饱了，却还是望着天空。它最想要的，好像不是这个。',
  'cage.opt2': '给笼子换一个漂亮的新罩子',
  'cage.res2': '笼子再漂亮，也还是笼子。',
  'cage.opt3': '打开笼门',
  'cage.res3': '它在门口停了一下，然后飞上大树，和朋友们一起唱了起来。这一次，是真的在唱歌。',
  'cage.povTitle': '倘使我是一只画眉',
  'cage.pov': '你刚才就是那只画眉。飞几下就撞到笼子，外面的天空却那么大。',
  'cage.ask': '笼子里的画眉“唱歌”，和树上的画眉唱歌，是一样的吗？说说你的想法。',
  'cage.verse': '笼鸡有食汤锅近，野鹤无粮天地宽。',
  'cage.verseBy': '古语',
  'cage.verseGloss': '笼里的鸡有吃的，可离汤锅也近；野外的鹤没有现成的粮食，天地却宽广。',
  'cage.know': '画眉已被列为国家二级保护野生动物，许多野生鸟类都不能随便捕捉和买卖。不过要记住：人工养大的宠物鸟（比如虎皮鹦鹉）不会在野外生活，不能随便放走——好好照顾它，才是对它负责。',
  'cage.book': '《护生画集》里常常画到笼中的鸟。丰子恺希望看画的人想一想：倘使我是它？',

  /* 6 · reading */
  'read.title': '读画',
  'read.animal': '丰子恺的画',
  'read.season': '四季',
  'read.intro': '丰子恺的画，第一眼看，只有简简单单几笔；再看一眼，心里就轻轻一动。我们来学着“读”他的画。',
  'read.tipsTitle': '读画的三把钥匙',
  'read.tip1t': '寥寥几笔',
  'read.tip1': '线条很少，却抓住了最要紧的东西。',
  'read.tip2t': '没有五官',
  'read.tip2': '画里的人常常没有眼睛、鼻子和嘴巴，可你从动作里就能看出他们的心情。',
  'read.tip3t': '画中有诗',
  'read.tip3': '画和题字合在一起，才是一个完整的故事。',
  'read.note': '有丰子恺原画的扫描图时，这里会直接展示原画；没有的话，会显示照着原画构图重画的示意图，并标明“示意图”。有机会一定要去看看原画。',
  'read.begin': '开始读画',
  'read.look': '看一看，想一想',
  'read.wrong': '再仔细看看画里的细节？',
  'read.right': '读懂了！',
  'read.nextPic': '下一幅',
  'read.stat': '第 {a}/{b} 幅',
  'read.r1.q': '小姑娘在做什么？',
  'read.r1.a': ['给凳子穿鞋子', '在修凳子', '把鞋子藏起来'],
  'read.r1.title': '阿宝两只脚，凳子四只脚',
  'read.r1.text': '阿宝是丰子恺的大女儿。她看凳子有四只脚，觉得凳子也该穿鞋，就把鞋子套在了凳子脚上，还得意地喊：“阿宝两只脚，凳子四只脚！”在孩子眼里，万物都有感觉。这幅画不在《护生画集》里，却藏着护生的种子：像孩子一样，把心放到别的事物身上。',
  'read.r1.quote': '我的心为四事所占据了：天上的神明与星辰，人间的艺术与儿童。',
  'read.r1.quoteBy': '丰子恺《儿女》',
  'read.r2.q': '地上有一团鸡毛。小鸡们为什么围着它？',
  'read.r2.a': ['它们以为那是妈妈', '它们在玩捉迷藏', '鸡毛里藏着米粒'],
  'read.r2.title': '母之羽',
  'read.r2.text': '这幅画收在《护生画集》第一集。那些羽毛，是母鸡妈妈的。妈妈已经不在了，小鸡们却不知道，还依偎在熟悉的羽毛旁边。',
  'read.r2.poem': '雏儿依残羽，殷殷恋慈母。母亡儿不知，犹复相环守。念此亲爱情，能勿凄心否。',
  'read.r3.q': '一只螃蟹跌倒了，另外两只在做什么？',
  'read.r3.a': ['扶它起来', '和它打架', '抢它的食物'],
  'read.r3.title': '生的扶持',
  'read.r3.text': '这幅画也收在《护生画集》第一集。题字只有十六个字，意思是：连螃蟹都懂得互相帮助，人难道还不如螃蟹吗？',
  'read.r3.poem': '一蟹失足，二蟹持扶。物知慈悲，人何不如。',
  'read.win': '你已经学会读丰子恺的画了。下一步，试着画一幅你自己的护生画吧！',
  'read.povTitle': '读画之后',
  'read.pov': '三幅画都没有画一张脸，却让人心里一动。这就是丰子恺的本事：用最少的笔墨，画出最真的心。',
  'read.ask': '三幅画里，你最喜欢哪一幅？它让你想起了自己的什么经历？',
  'read.verse': '护生者，护心也。',
  'read.verseBy': '丰子恺',
  'read.verseGloss': '爱护生命，就是守护我们自己的心。',
  'read.know': '“漫画”这个词，是从“子恺漫画”开始在中国流行起来的，所以很多人称丰子恺为中国漫画的开创者。',
  'read.book': '《护生画集》里的画，大多就是这样：一幅画，一首诗，一个让人停下来想一想的瞬间。',

  /* studio */
  'studio.title': '我的护生画',
  'studio.intro': '现在轮到你当画家了！画一只你见过的小动物，或者一个你想守护的生命。也可以用贴画来帮忙。',
  'studio.brush': '毛笔',
  'studio.thin': '细',
  'studio.mid': '中',
  'studio.thick': '粗',
  'studio.ink': '浓墨',
  'studio.lightInk': '淡墨',
  'studio.colors': '淡彩',
  'studio.green': '草绿',
  'studio.blue': '花青',
  'studio.ochre': '赭石',
  'studio.red': '胭脂',
  'studio.stickers': '贴画',
  'studio.stickerHint': '选一个贴画，再点画面把它放上去。',
  'studio.drawHint': '在画纸上按住拖动来画画。',
  'studio.size': '贴画大小',
  'studio.flip': '左右翻转',
  'studio.undo': '撤销',
  'studio.clear': '清空',
  'studio.clearAsk': '真的要清空整幅画吗？',
  'studio.yes': '清空',
  'studio.no': '不了',
  'studio.words': '题字',
  'studio.titleLabel': '画的题目',
  'studio.titlePh': '例如：回家的蚂蚁',
  'studio.poemLabel': '题诗（每行一句，最多四句）',
  'studio.poemPh': '倘使我是它，\n也想回家。',
  'studio.inspire': '给我一点灵感',
  'studio.sealLabel': '印章上的字',
  'studio.sealPh': '最多四个字',
  'studio.done': '完成，装裱起来',
  'studio.preview': '你的护生画',
  'studio.edit': '继续修改',
  'studio.untitled': '无题',
  'studio.inspirations': [
    '倘使我是它，\n也想回家。',
    '小小一只蚁，\n也有家要回。',
    '轻轻走过草地，\n不踩一朵小花。',
    '打开窗子，\n让飞蛾飞回月光里。',
    '鸟儿在枝头唱歌，\n我在树下静静听。',
    '一条小鱼，\n一池清水。',
  ],
  'studio.sticker.cat': '白象',
  'studio.sticker.bird': '画眉',
  'studio.sticker.swallow': '燕子',
  'studio.sticker.fish': '鱼',
  'studio.sticker.ant': '蚂蚁',
  'studio.sticker.butterfly': '蝴蝶',
  'studio.sticker.chick': '小鸡',
  'studio.sticker.crab': '螃蟹',
  'studio.sticker.kid': '孩子',
  'studio.sticker.moon': '月亮',
  'studio.sticker.flower': '小花',
  'studio.sticker.willow': '柳枝',

  /* quiz */
  'quiz.title': '护生小博士',
  'quiz.intro': '一共 {n} 道题，答对 {pass} 道就能领取“护生小画师”证书。答错也没关系，每道题后面都有讲解。',
  'quiz.go': '开始答题',
  'quiz.q': '第 {a}/{b} 题',
  'quiz.right': '答对了！',
  'quiz.wrong': '正确答案是：{a}',
  'quiz.next': '下一题',
  'quiz.finish': '看看成绩',
  'quiz.score': '你答对了 {a}/{b} 题',
  'quiz.pass': '太棒了！这是你的证书。',
  'quiz.fail': '差一点点！再翻翻画册，然后再来试试吧。',
  'quiz.retry': '再答一次',
  'quiz.certBtn': '看我的证书',
  'cert.title': '护生小画师',
  'cert.word': '证书',
  'cert.body': '{name}同学走进了丰子恺的《护生画集》，画完了 {pages} 页画册，收集了 {seals} 枚慈心印，并通过了护生小博士问答。愿你把这颗护生的心，带到每一天。',
  'cert.anon': '小画师',
  'cert.quote': '护生者，护心也。',
  'cert.quoteBy': '丰子恺',
  'cert.issuer': '护生之约 · 画册',

  /* teacher */
  'teach.title': '给老师的话',
  'teach.who.t': '适合对象',
  'teach.who': '小学三年级到初中（约8—14岁）。每一页3—5分钟，完整玩一遍约40分钟。电脑、平板、手机和投影都可以使用，不需要安装。',
  'teach.goals.t': '学习目标',
  'teach.goals': [
    '了解丰子恺与弘一法师的约定，以及《护生画集》六集四百五十幅的来历。',
    '学会“读画”：从简单的线条和题诗中读出情感与道理。',
    '用“倘使我是它”练习换位思考，培养同理心。',
    '把护生延伸到今天：保护栖息地、减少光污染、科学地对待野生动物。',
    '创作一幅自己的护生画，配上题诗。',
  ],
  'teach.flow.t': '一节课的建议（40分钟）',
  'teach.flow': [
    '导入（5分钟）：全班一起看“序 · 一个约定”，讨论“世寿所许，定当遵嘱”是什么意思。',
    '游戏（15分钟）：两人一组，每组画一到两页。请学生留意每页的“倘使我是它”。',
    '读画（10分钟）：用投影一起玩第六页“读画”，请学生说说画里没有画出来的东西。',
    '创作（10分钟）：在“末页”画一幅自己的护生画，配上题诗，全班分享。',
  ],
  'teach.ask.t': '讨论问题',
  'teach.about.t': '关于内容',
  'teach.about': '游戏中的插图都是仿丰子恺笔意的原创绘画，不是原作；“读画”一页是照着原画构图重新画的示意图。建议在课堂上配合展示《护生画集》原画。诗句与史实已尽量核对，不同版本的题字可能略有出入。',
  'teach.links.t': '直接打开某一页',
  'teach.links': '在网址后面加上 #ants（扫地）、#pond（清池）、#moths（纱灯）、#nest（望母归）、#cage（笼门）、#reading（读画）、#studio（我的护生画）或 #quiz（护生小博士），就能直接打开那一页。',
  'teach.orig.t': '丰子恺原画',
  'teach.orig': '游戏会展示丰子恺的原画：把扫描图按下面的文件名放进 images/paintings/ 文件夹就行。找不到扫描图时，游戏会显示标明“示意图”的重绘草图。这台设备上现在的情况：',
  'teach.found': '已找到原画',
  'teach.missing': '还没有扫描图',
  'teach.checking': '检查中……',
  'teach.rights': '丰子恺于1975年去世，按中国著作权法，他的作品已于2026年1月1日进入公有领域；《护生画集》第一集（1929年）和1920年代的子恺漫画在美国也已进入公有领域。',
  'teach.settings.t': '设置',
  'teach.easy': '慢速模式',
  'teach.easyDesc': '动作更慢、目标更大，适合低年级或需要更多时间的学生。',
  'teach.reset': '清除这台设备上的进度',
  'teach.resetAsk': '确定要清除吗？画册、印章、画作草稿和证书记录都会被清除。',
  'teach.resetYes': '清除',
  'teach.resetNo': '不清除',
  'teach.resetDone': '进度已清除。',
};

STR.en = {
  'app.name': '护生之约',
  'app.sub': 'Step inside Feng Zikai’s Paintings for the Preservation of Life',
  'app.lede': 'A blank album, six small lives, and a promise kept for more than forty years.',
  'app.credit': 'The pictures are original drawings in the spirit of Feng Zikai’s style, not his paintings.',

  'title.start': 'Open the album',
  'title.continue': 'Continue my album',
  'title.teacher': 'For teachers',
  'title.nameLabel': 'Write your name on the album cover',
  'title.namePh': 'Your name (optional)',
  'title.nameHint': 'Your name will be carved into a red seal and stamped on your paintings.',

  'ui.album': 'Album',
  'ui.cover': 'Cover',
  'ui.backToAlbum': 'Back to the album',
  'ui.sound': 'Sound',
  'ui.soundOn': 'Sound on',
  'ui.soundOff': 'Sound off',
  'ui.lang': '中文',
  'ui.langName': 'English',
  'ui.next': 'Next',
  'ui.prev': 'Back',
  'ui.start': 'Start',
  'ui.continue': 'Continue',
  'ui.ok': 'OK',
  'ui.toPage': 'Turn to the page',
  'ui.collect': 'Add to my album',
  'ui.again': 'Play again',
  'ui.close': 'Close',
  'ui.seals': 'kindness seals',
  'ui.sealsN': '{n} kindness seals',
  'ui.pageN': 'Page {n}',
  'ui.pov': 'If I were it…',
  'ui.talk': 'Think and talk',
  'ui.know': 'Did you know?',
  'ui.fromBook': 'From the collection',
  'ui.today': 'Protecting life today',
  'ui.save': 'Save image',
  'ui.saving': 'Preparing the image…',
  'ui.saved': 'Image saved.',
  'ui.saveDeclined': 'Not saved. Tap again whenever you’re ready.',
  'ui.saveManual': 'Right-click the image (or long-press on a phone) to save it.',
  'ui.catTap': 'Tap Baixiang the cat for a little story',
  'ui.catName': 'Baixiang',
  'ui.meow': 'Meow~',
  'ui.easyOn': 'Gentle mode is on',
  'ui.loading': 'Unrolling the scroll…',
  'ui.close2': 'Hide',
  'ui.rotate': 'Turn your phone sideways for a bigger picture.',

  'cat.facts': [
    'Feng Zikai grew up in Shimenwan, a river town in Tongxiang, Zhejiang, full of bridges and willows.',
    'Feng’s home was called Yuanyuan Hall. Master Hongyi suggested he draw lots for the name, and both times he drew the character 缘 (yuan)!',
    'The word manhua (comics) caught on in China through “Zikai Manhua,” a collection of Feng’s drawings.',
    'Feng Zikai loved children. Many of his paintings show his own kids.',
    'Feng often left the eyes, nose and mouth off the people he painted. Why do you think he did that?',
    'Do you know Li Shutong’s song “Farewell”? “Beyond the long pavilion, beside the ancient road…”',
    'My favourite thing is a nap in the sun. Meow~',
    'If I were it… you can ask yourself that every time you meet a small living thing.',
  ],

  'orig.real': 'Original by Feng Zikai',
  'orig.sketch': 'Sketch · scan of the original not added yet',
  'orig.by': 'painting by Feng Zikai',
  'orig.heading': 'Feng Zikai’s original painting',
  'orig.unlocked': 'This page unlocked one of Feng Zikai’s original paintings',
  'leaf.verseCard': 'A line for this page',

  'album.title': 'My Album of Protecting Life',
  'album.titleNamed': '{name}’s Album of Protecting Life',
  'album.progress': '{done} of 6 pages painted · {seals} kindness seals',
  'album.todo': 'Not painted yet',
  'album.done': 'Painted',
  'album.read': 'Read',
  'album.finish': 'All six pages are painted! Feng Zikai kept his promise to his teacher, and you have finished your own album.',
  'album.prologue': 'Prologue · A Promise',
  'album.prologueDesc': 'Feng Zikai’s promise to his teacher',
  'album.studio': 'Last Page · My Own Painting',
  'album.studioDesc': 'Paint your own picture, add a poem, and stamp your seal.',
  'album.quiz': 'The Kindness Quiz',
  'album.quizDesc': 'Answer the questions and earn your certificate.',
  'album.quizPassed': 'Certificate earned',
  'album.hint': 'Paint the pages in order, or start with any page you like.',

  'pro.title': 'A Promise',
  'pro.p1.t': 'A Young Art Student',
  'pro.p1': 'More than a hundred years ago, at the Zhejiang First Normal School in Hangzhou, a student named Feng Zikai studied painting and music with his teacher, Li Shutong. Li was gifted at many arts. He even wrote a song that is still sung today, “Farewell”: “Beyond the long pavilion, beside the ancient road, fragrant grass stretches to the sky…”',
  'pro.p2.t': 'The Teacher Becomes a Monk',
  'pro.p2': 'In 1918, Li Shutong became a Buddhist monk in Hangzhou, known as Master Hongyi. He gave up almost all of his arts except calligraphy. But he and his student stayed close.',
  'pro.p3.t': 'Fifty Paintings for a Birthday',
  'pro.p3': 'In 1929 the teacher turned fifty. As a birthday gift, Feng painted fifty pictures, and the teacher matched each one with a poem in his own calligraphy. Every picture says the same thing: care for all living things. This became Volume One of Paintings for the Preservation of Life.',
  'pro.p4.t': 'A Promise',
  'pro.p4': 'Ten years later, for the teacher’s sixtieth birthday, Feng painted sixty more. The teacher wrote to ask for seventy paintings at seventy, eighty at eighty, ninety at ninety, and one hundred at one hundred. Feng wrote back:',
  'pro.p4.quote': '世寿所许，定当遵嘱。',
  'pro.p4.gloss': '“As long as my life allows, I will do as you ask.”',
  'pro.p5.t': 'The Promise Lives On',
  'pro.p5': 'Master Hongyi died in 1942. But the promise remained. Through war and hard times, Feng kept going, volume after volume: seventy paintings, eighty, ninety…',
  'pro.p6.t': 'Four Hundred and Fifty',
  'pro.p6': 'In 1973, Feng quietly finished the last hundred. Six volumes, 450 paintings: it took him more than forty years to keep his word. Tap each volume on the shelf to see its story.',
  'pro.p7.t': 'Now It’s Your Turn',
  'pro.p7': 'Feng Zikai said: “To protect life is to protect the heart.” Caring for small lives is also how we keep our own hearts kind. Now this blank album is yours.',
  'pro.p7.cat': 'Meow! I’m Baixiang, which means “White Elephant.” The Feng family once had a white cat with that name, and Feng wrote an essay about it. Let me keep you company, page by page!',
  'pro.open': 'Open my album',
  'pro.shelfHint': 'Tap a volume',
  'pro.vol': [
    { n: 'Volume 1', year: '1929', count: '50 paintings', by: 'Poems and calligraphy by Master Hongyi', note: 'For the teacher’s 50th birthday' },
    { n: 'Volume 2', year: '1940', count: '60 paintings', by: 'Calligraphy by Master Hongyi', note: 'For the teacher’s 60th birthday' },
    { n: 'Volume 3', year: '1949', count: '70 paintings', by: 'Calligraphy by Ye Gongchuo', note: 'The teacher had died, but the promise lived on' },
    { n: 'Volume 4', year: '1960', count: '80 paintings', by: 'Calligraphy by Zhu Youlan', note: '' },
    { n: 'Volume 5', year: '1965', count: '90 paintings', by: 'Calligraphy by Yu Yu', note: '' },
    { n: 'Volume 6', year: '1973', count: '100 paintings', by: 'Calligraphy by Zhu Youlan', note: 'Finished quietly in hard times; published in 1979' },
  ],

  'ch.intro': 'The story of this page',
  'ch.howto': 'How to play',
  'ch.skipIntro': 'Start now',
  'ch.done': 'This page is painted!',
  'ch.sealsGot': 'You earned {n} kindness seals',
  'ch.sealWhy3': 'You were so careful: every small life is safe.',
  'ch.sealWhy2': 'Well done! Next time, try going even slower and gentler.',
  'ch.sealWhy1': 'Painted! Play again and see if you can be a little more careful.',
  'ch.replay': 'Replay this page',

  'ants.title': 'Sweeping Gently',
  'ants.animal': 'Ants',
  'ants.season': 'Spring',
  'ants.intro': 'Spring. Willow leaves cover the courtyard. Pick up the broom and sweep! But first, look down: a line of tiny guests is on its way home.',
  'ants.howto': 'Press and drag the broom to sweep leaves away, or tap a leaf to pick it up gently. Don’t touch the ants. Slow is fine!',
  'ants.stat': 'Leaves {a}/{b} · Ants startled {c}',
  'ants.oops': 'Oops, you startled it!',
  'ants.poke': 'Shh, it’s busy getting home.',
  'ants.rain': 'The ants are moving house… rain must be coming. They need to hurry home.',
  'ants.gentle': 'Nice and gentle.',
  'ants.win': 'All clean! And every little ant got home safely.',
  'ants.povTitle': 'If I were an ant…',
  'ants.pov': 'If you were an ant, a broom coming down would look like a whole bamboo forest falling from the sky. You’d be carrying one grain of rice, just trying to get home.',
  'ants.ask': 'Where have you seen ants? What will you do the next time you meet them?',
  'ants.verseBy': 'Old saying',
  'ants.verseEn': 'When sweeping, take care not to harm the ants.',
  'ants.know': 'One ant colony can have thousands of ants, each with a job: some find food, some look after the young. Before rain the air gets damp and ants often move house, which is why a Chinese saying goes: “When ants move house, rain is coming.”',
  'ants.book': 'The collection is full of small lives like these: ants, butterflies, frogs, little birds. To Feng Zikai, each of them had a home, just as we do.',

  'pond.title': 'A Clear Pond',
  'pond.animal': 'Fish',
  'pond.season': 'Summer',
  'pond.intro': 'In summer, the pond is home to the fish. But someone has thrown trash into the water, and one fish is caught in an old fishing line.',
  'pond.howto': 'Tap trash in the water to scoop it out with the net. Careful not to scoop the fish! Tap the fish caught in fishing line to set it free.',
  'pond.stat': 'Trash {a}/{b} · Freed {c}/1 · Fish startled {d}',
  'pond.oops': 'The fish got a fright!',
  'pond.freed': 'Free! It can swim easily again.',
  'pond.tangledHint': 'That fish is caught in fishing line. Tap it!',
  'pond.win': 'The water is clear. The fish have their home back.',
  'pond.povTitle': 'If I were a fish…',
  'pond.pov': 'If you were a fish, a plastic bag floating overhead would be like a dark cloud that never goes away.',
  'pond.ask': 'Is there a river, pond or stream near your home? What could make life better for the creatures there?',
  'pond.verseBy': 'Du Fu',
  'pond.verseEn': 'In the fine rain, fish rise to the surface; in the light breeze, swallows glide aslant.',
  'pond.know': 'Some people buy fish to “set them free.” But releasing fish from somewhere else into a river can harm the creatures already living there. The best way to protect life is to protect its home: keep the water clean.',
  'pond.book': 'In Feng Zikai’s day there was nowhere near this much plastic in the water. Today, protecting life also means looking after rivers, forests and the sky.',

  'moth.title': 'The Gauze Lamp',
  'moth.animal': 'Moths',
  'moth.season': 'Summer night',
  'moth.intro': 'A summer night. An oil lamp burns on the desk. Moths drift in through the window, one after another, heading straight for the flame…',
  'moth.howto': 'Tap a moth to guide it back out the window into the moonlight. Don’t let it touch the flame!',
  'moth.stat': 'Guided out {a} · Burned {b}',
  'moth.hot': 'Too hot!',
  'moth.saved': 'Off you go: the moonlight is that way.',
  'moth.gauzeCue': 'Baixiang found a gauze shade! Drag it over the lamp.',
  'moth.gauzeOn': 'With the shade on, the lamp still shines, but the moths can’t get burned.',
  'moth.moonAsk': 'The moon is so bright tonight. Shall we blow out the lamp and watch it together?',
  'moth.blow': 'Blow out the lamp',
  'moth.win': 'The lamp is out, and the moths have all flown off into the moonlight.',
  'moth.povTitle': 'If I were a moth…',
  'moth.pov': 'If you were a moth, that bright flame would be a puzzle that makes you forget which way is up. You could only circle it, round and round.',
  'moth.ask': 'The gauze shade is a small invention that protects small lives. Can you think of other clever ideas like it?',
  'moth.verseBy': 'Su Shi',
  'moth.verseEn': 'Always leave some rice out for the mice; out of pity for the moths, leave the lamp unlit.',
  'moth.know': 'Why do moths circle lamps? Scientists have found that flying insects keep their backs turned toward the brightest light to tell up from down. A lamp confuses them, so they fly round and round it. So switch off lights you don’t need at night.',
  'moth.book': 'Remember the old saying on page one, “When sweeping, take care not to harm the ants”? Its next line is “Cherish the moths: put a gauze shade on the lamp.”',

  'nest.title': 'Waiting for Mother',
  'nest.animal': 'Chicks',
  'nest.season': 'Autumn',
  'nest.intro': 'Autumn. There is a nest high in a big tree. The mother bird has flown off to find insects, and her chicks are waiting for her. Down below, a boy raises his slingshot…',
  'nest.boy1': 'Watch me knock that bird off the branch!',
  'nest.ask': 'How will you talk him out of it?',
  'nest.opt1': 'Stop! I’m telling the teacher!',
  'nest.res1': 'Hmph. The teacher isn’t here.',
  'nest.hint1': 'Scaring him just means he’ll do it when no one is looking. Try another way?',
  'nest.opt2': 'Shh, listen. There are chicks up in the tree. They’re waiting for their mother to come home.',
  'nest.res2': '…That bird is their mother?',
  'nest.opt3': 'Hitting birds is boring. Let’s go play football!',
  'nest.res3': 'But I want to hit birds.',
  'nest.hint3': 'A new game won’t stop him tomorrow. He needs to understand it for himself.',
  'nest.good': 'He lowers the slingshot. The poet Bai Juyi wrote a poem about exactly this:',
  'nest.poemBy': 'Bai Juyi, “Birds”',
  'nest.poemEn': 'Who says the lives of creatures are small? They have the same flesh and bone, the same skin as ours. I urge you, do not strike the bird on the branch: its young in the nest are watching for their mother to come home.',
  'nest.wind': 'Suddenly, a strong gust of wind! A chick tumbles out of the nest.',
  'nest.boy2': 'Let’s put it back together!',
  'nest.howto': 'Press and hold the chick, then carry it slowly back to the nest. Too fast and it gets scared; bumping a branch hurts.',
  'nest.stat': 'Scared {a} · Bumps {b}',
  'nest.fearLabel': 'How scared is the chick?',
  'nest.fast': 'Slower… it’s trembling. Stop for a moment and let it calm down.',
  'nest.calm': 'There. It isn’t scared any more.',
  'nest.bump': 'Watch the branch!',
  'nest.win': 'The mother bird is back! The family is together again.',
  'nest.povTitle': 'If I were a chick…',
  'nest.pov': 'If you were a chick that just fell from the nest, the ground would feel huge and cold, and your mother would be nowhere in sight. All you could do is call and call.',
  'nest.ask2': 'When you want someone to stop hurting a living thing, what way of speaking works best? Why?',
  'nest.verseBy': 'Bai Juyi, “Birds”',
  'nest.verseEn': 'Do not strike the bird on the branch: its young in the nest are waiting for their mother.',
  'nest.know': 'If you find a young bird on the ground that has most of its feathers and can hop, it is probably learning to fly, and its parents are close by. Watch from a distance and leave it alone. Only a chick without proper feathers that has fallen out needs to be put back. And the idea that parent birds abandon a chick touched by people is a myth.',
  'nest.book': 'Feng Zikai painted many mother birds with their young. On page six, “Reading Paintings,” you’ll see one of the most moving.',

  'cage.title': 'The Cage Door',
  'cage.animal': 'Thrush',
  'cage.season': 'Winter',
  'cage.intro': 'A birdcage hangs under the eaves. Inside is a hwamei thrush that was caught in the hills. Every day it “sings” in its cage…',
  'cage.intro2': 'This time, you are the thrush in the cage.',
  'cage.howto': 'Tap the picture or press Space to flap. Tap the left or right side, or use the arrow keys, to fly left or right.',
  'cage.bump': 'Bump!',
  'cage.th1': 'It’s so big out there…',
  'cage.th2': 'My friends are calling me…',
  'cage.th3': 'The sky is so big, and I have only this much.',
  'cage.outside': 'Now you’re back outside the cage. What will you do?',
  'cage.opt1': 'Give it more seed and fresh water',
  'cage.res1': 'It has plenty to eat, but it keeps gazing at the sky. That doesn’t seem to be what it wants most.',
  'cage.opt2': 'Get a beautiful new cover for the cage',
  'cage.res2': 'A prettier cage is still a cage.',
  'cage.opt3': 'Open the cage door',
  'cage.res3': 'It pauses at the door, then flies up into the big tree and sings with its friends. This time, it really is singing.',
  'cage.povTitle': 'If I were a thrush…',
  'cage.pov': 'You were that thrush just now: a few wingbeats and you hit the bars, while the sky outside went on forever.',
  'cage.ask': 'Is the caged thrush’s “singing” the same as the free thrush’s song? What do you think?',
  'cage.verseBy': 'Old saying',
  'cage.verseEn': 'The caged chicken has food, but the cooking pot is near; the wild crane has no grain, but heaven and earth are wide.',
  'cage.know': 'In China the hwamei thrush is now a protected wild species, and many wild birds may not be caught or sold. But remember: pet birds raised by people, like budgies, can’t survive in the wild, so never just let them go. Caring for them well is the responsible thing to do.',
  'cage.book': 'Caged birds appear again and again in the collection. Feng Zikai wanted viewers to ask themselves: what if I were that bird?',

  'read.title': 'Reading Paintings',
  'read.animal': 'Feng’s paintings',
  'read.season': 'All seasons',
  'read.intro': 'Feng Zikai’s paintings look simple at first: just a few strokes. Look again, and something stirs in your heart. Let’s learn to “read” them.',
  'read.tipsTitle': 'Three keys for reading a painting',
  'read.tip1t': 'A few strokes',
  'read.tip1': 'Very few lines, but they catch what matters most.',
  'read.tip2t': 'No faces',
  'read.tip2': 'His people often have no eyes, nose or mouth, yet you can read their feelings from how they stand and move.',
  'read.tip3t': 'Poem and picture',
  'read.tip3': 'The painting and its words together tell the whole story.',
  'read.note': 'Where a scan of the original is available, you’ll see Feng Zikai’s own painting; otherwise you’ll see a redrawn sketch that follows its composition, labelled as a sketch. If you can, go and see the real paintings!',
  'read.begin': 'Start reading',
  'read.look': 'Look closely',
  'read.wrong': 'Look again at the details?',
  'read.right': 'You read it!',
  'read.nextPic': 'Next painting',
  'read.stat': 'Painting {a} of {b}',
  'read.r1.q': 'What is the little girl doing?',
  'read.r1.a': ['Putting shoes on the stool', 'Fixing the stool', 'Hiding the shoes'],
  'read.r1.titleEn': 'Abao Has Two Feet, the Stool Has Four',
  'read.r1.text': 'Abao was Feng Zikai’s eldest daughter. Seeing that the stool had four feet, she decided it needed shoes too, slipped shoes onto its legs, and proudly shouted: “Abao has two feet, the stool has four!” To a child, everything has feelings. This painting is not in the collection, but it holds the collection’s seed: putting your heart into other beings, the way a child does.',
  'read.r1.quoteEn': 'My heart is taken up by four things: the gods and the stars in the sky, and art and children on earth.',
  'read.r1.quoteBy': 'Feng Zikai, “Sons and Daughters”',
  'read.r2.q': 'There is a bundle of feathers on the ground. Why are the chicks gathered around it?',
  'read.r2.a': ['They think it’s their mother', 'They’re playing hide-and-seek', 'There’s rice hidden in the feathers'],
  'read.r2.titleEn': 'Mother’s Feathers',
  'read.r2.text': 'This painting is in Volume One of the collection. The feathers belonged to the mother hen. She is gone, but the chicks don’t know it; they still nestle against the feathers they know.',
  'read.r2.poemEn': 'The chicks cling to the fallen feathers, longing for their loving mother. She has died, and they do not know; still they gather round and keep watch. Thinking of such love, how can our hearts not ache?',
  'read.r3.q': 'One crab has stumbled. What are the other two doing?',
  'read.r3.a': ['Helping it up', 'Fighting it', 'Taking its food'],
  'read.r3.titleEn': 'Helping Each Other Live',
  'read.r3.text': 'This painting is also in Volume One. Its inscription is just sixteen characters long. It means: even crabs know how to help one another. Should people do any less?',
  'read.r3.poemEn': 'One crab loses its footing; two crabs hold it up. If creatures know compassion, how can people do less?',
  'read.win': 'You’ve learned to read Feng Zikai’s paintings. Next, try painting one of your own!',
  'read.povTitle': 'After reading',
  'read.pov': 'Not one of these paintings shows a face, yet each one moves us. That was Feng Zikai’s gift: the fewest brushstrokes, the truest feelings.',
  'read.ask': 'Which of the three do you like best? Does it remind you of anything in your own life?',
  'read.verseBy': 'Feng Zikai',
  'read.verseEn': 'To protect life is to protect the heart.',
  'read.know': 'The word manhua (comics) caught on in China through “Zikai Manhua,” a collection of Feng’s drawings, which is why many people see him as a founder of Chinese manhua.',
  'read.book': 'Most paintings in the collection work just this way: one picture, one poem, one moment that makes you stop and think.',

  'studio.title': 'My Own Painting',
  'studio.intro': 'Now you’re the painter! Draw a creature you’ve met, or a life you’d like to protect. The stickers can help.',
  'studio.brush': 'Brush',
  'studio.thin': 'Fine',
  'studio.mid': 'Medium',
  'studio.thick': 'Bold',
  'studio.ink': 'Dark ink',
  'studio.lightInk': 'Light ink',
  'studio.colors': 'Colour wash',
  'studio.green': 'Leaf green',
  'studio.blue': 'Indigo',
  'studio.ochre': 'Ochre',
  'studio.red': 'Rouge',
  'studio.stickers': 'Stickers',
  'studio.stickerHint': 'Pick a sticker, then tap the paper to place it.',
  'studio.drawHint': 'Press and drag on the paper to paint.',
  'studio.size': 'Sticker size',
  'studio.flip': 'Flip',
  'studio.undo': 'Undo',
  'studio.clear': 'Clear',
  'studio.clearAsk': 'Clear the whole painting?',
  'studio.yes': 'Clear it',
  'studio.no': 'Keep it',
  'studio.words': 'Words',
  'studio.titleLabel': 'Title',
  'studio.titlePh': 'e.g. The Ant Going Home',
  'studio.poemLabel': 'Poem (one line per row, up to four)',
  'studio.poemPh': 'If I were you,\nI’d want to go home too.',
  'studio.inspire': 'Give me an idea',
  'studio.sealLabel': 'Seal text',
  'studio.sealPh': 'Up to 4 characters, or your initials',
  'studio.done': 'Finish and mount it',
  'studio.preview': 'Your painting',
  'studio.edit': 'Keep editing',
  'studio.untitled': 'Untitled',
  'studio.inspirations': [
    'If I were you,\nI’d want to go home too.',
    'A tiny ant\nhas a home to go back to.',
    'I walk softly on the grass\nso every flower can stay.',
    'I open the window\nand the moth flies home to the moon.',
    'A bird sings on the branch;\nI listen quietly below.',
    'One little fish,\none clear pond.',
  ],
  'studio.sticker.cat': 'Cat',
  'studio.sticker.bird': 'Thrush',
  'studio.sticker.swallow': 'Swallow',
  'studio.sticker.fish': 'Fish',
  'studio.sticker.ant': 'Ant',
  'studio.sticker.butterfly': 'Butterfly',
  'studio.sticker.chick': 'Chick',
  'studio.sticker.crab': 'Crab',
  'studio.sticker.kid': 'Child',
  'studio.sticker.moon': 'Moon',
  'studio.sticker.flower': 'Flower',
  'studio.sticker.willow': 'Willow',

  'quiz.title': 'The Kindness Quiz',
  'quiz.intro': 'There are {n} questions. Get {pass} right to earn your Little Painter of Life certificate. Wrong answers are fine: every question comes with an explanation.',
  'quiz.go': 'Start the quiz',
  'quiz.q': 'Question {a} of {b}',
  'quiz.right': 'Correct!',
  'quiz.wrong': 'The answer is: {a}',
  'quiz.next': 'Next question',
  'quiz.finish': 'See my score',
  'quiz.score': 'You got {a} out of {b}',
  'quiz.pass': 'Wonderful! Here is your certificate.',
  'quiz.fail': 'So close! Look through your album again, then have another try.',
  'quiz.retry': 'Try again',
  'quiz.certBtn': 'See my certificate',
  'cert.title': 'Little Painter of Life',
  'cert.word': 'Certificate',
  'cert.body': '{name} stepped into Feng Zikai’s Paintings for the Preservation of Life, painted {pages} album pages, collected {seals} kindness seals, and passed the Kindness Quiz. May you carry this caring heart into every day.',
  'cert.anon': 'Our young painter',
  'cert.quoteEn': 'To protect life is to protect the heart.',
  'cert.quoteBy': 'Feng Zikai',
  'cert.issuer': '护生之约 · A Promise to Protect Life',

  'teach.title': 'For Teachers',
  'teach.who.t': 'Who it’s for',
  'teach.who': 'Grades 3–8 (about ages 8–14). Each page takes 3–5 minutes; the whole game takes about 40 minutes. It works on computers, tablets, phones and projectors, with nothing to install.',
  'teach.goals.t': 'Learning goals',
  'teach.goals': [
    'Know the story of Feng Zikai’s promise to Master Hongyi, and how six volumes and 450 paintings came to be.',
    'Learn to “read” a painting: find the feeling and the message in simple lines and an inscription.',
    'Practise empathy with the question “What if I were it?”',
    'Connect protecting life to today: habitats, light pollution, and caring for wild animals wisely.',
    'Create a painting of one’s own, with a short poem.',
  ],
  'teach.flow.t': 'A 40-minute lesson',
  'teach.flow': [
    'Warm-up (5 min): watch “Prologue · A Promise” together and discuss what “As long as my life allows, I will do as you ask” means.',
    'Play (15 min): in pairs, each pair paints one or two pages. Ask students to notice the “If I were it…” moment on each page.',
    'Reading (10 min): play page six, “Reading Paintings,” together on the projector. Ask what the paintings leave out.',
    'Create (10 min): each student paints their own picture on the last page, adds a poem, and shares it with the class.',
  ],
  'teach.ask.t': 'Discussion questions',
  'teach.about.t': 'About the content',
  'teach.about': 'All illustrations are original drawings in the spirit of Feng Zikai’s style, not reproductions; the “Reading Paintings” page redraws the compositions of real works. Show the original paintings in class alongside the game. Quotations and dates have been checked carefully, but inscriptions can differ slightly between editions.',
  'teach.links.t': 'Link straight to a page',
  'teach.links': 'Add #ants, #pond, #moths, #nest, #cage, #reading, #studio or #quiz to the end of the address to open that page directly.',
  'teach.orig.t': 'Feng Zikai’s originals',
  'teach.orig': 'The game shows Feng Zikai’s original paintings: put a scan of each one into the images/paintings/ folder under the file name listed below. If a scan is missing, the game shows a redrawn sketch labelled as a sketch. Status on this device:',
  'teach.found': 'Original found',
  'teach.missing': 'No scan yet',
  'teach.checking': 'Checking…',
  'teach.rights': 'Feng Zikai died in 1975, so under Chinese copyright law his work entered the public domain on 1 January 2026. Volume 1 of the collection (1929) and his 1920s Zikai Manhua drawings are also public domain in the United States.',
  'teach.settings.t': 'Settings',
  'teach.easy': 'Gentle mode',
  'teach.easyDesc': 'Slower movement and bigger targets, for younger players or anyone who wants more time.',
  'teach.reset': 'Clear progress on this device',
  'teach.resetAsk': 'Are you sure? Album pages, seals, painting drafts and certificate records will all be cleared.',
  'teach.resetYes': 'Clear',
  'teach.resetNo': 'Keep',
  'teach.resetDone': 'Progress cleared.',
};

/* The quiz: each question has a Chinese and an English version.
 * `a` lists the options with the correct one first; the game shuffles them. */
window.QUIZ = [
  {
    zh: { q: '《护生画集》一共有几集？', a: ['六集', '三集', '十集'], why: '从1929年到1973年，丰子恺一共画了六集。' },
    en: { q: 'How many volumes does the collection have?', a: ['Six', 'Three', 'Ten'], why: 'Between 1929 and 1973, Feng Zikai painted six volumes.' },
  },
  {
    zh: { q: '六集加起来，一共有多少幅画？', a: ['450幅', '100幅', '1000幅'], why: '50＋60＋70＋80＋90＋100＝450。' },
    en: { q: 'How many paintings are there in all six volumes?', a: ['450', '100', '1,000'], why: '50 + 60 + 70 + 80 + 90 + 100 = 450.' },
  },
  {
    zh: { q: '丰子恺和谁约定画《护生画集》？', a: ['他的老师弘一法师（李叔同）', '他的学生', '他的邻居'], why: '李叔同是丰子恺的美术和音乐老师，后来出家成了弘一法师。' },
    en: { q: 'Who did Feng Zikai make his promise to?', a: ['His teacher, Master Hongyi (Li Shutong)', 'His student', 'His neighbour'], why: 'Li Shutong taught Feng art and music, and later became the monk Master Hongyi.' },
  },
  {
    zh: { q: '第一集为什么正好是五十幅？', a: ['为老师五十岁生日祝寿', '纸只够画五十张', '一年有五十个星期'], why: '1929年老师五十岁，丰子恺用五十幅画为他祝寿。' },
    en: { q: 'Why did Volume One have exactly fifty paintings?', a: ['For the teacher’s fiftieth birthday', 'There was only enough paper for fifty', 'Because a year has fifty weeks'], why: 'The teacher turned fifty in 1929, and Feng painted fifty pictures for his birthday.' },
  },
  {
    zh: { q: '丰子恺回信说“世寿所许，定当遵嘱”，是什么意思？', a: ['只要我还活着，一定照您说的做', '我太忙了，以后再说吧', '请您再说一遍'], why: '这八个字，丰子恺用四十多年守住了。' },
    en: { q: 'Feng replied “世寿所许，定当遵嘱.” What did he mean?', a: ['As long as I live, I will do as you ask', 'I’m too busy, maybe later', 'Please say that again'], why: 'Feng kept those eight characters for more than forty years.' },
  },
  {
    zh: { q: '丰子恺说：“护生者，护____也。”', a: ['心', '身', '林'], why: '爱护生命，其实是在守护我们自己的心。' },
    en: { q: 'Feng Zikai said: “To protect life is to protect the ____.”', a: ['heart', 'body', 'forest'], why: 'Caring for living things is how we look after our own hearts.' },
  },
  {
    zh: { q: '在《母之羽》里，小鸡们为什么围着那团羽毛？', a: ['它们以为那是妈妈', '它们在玩游戏', '羽毛里有米粒'], why: '那是母鸡妈妈的羽毛，小鸡们不知道妈妈已经不在了。' },
    en: { q: 'In “Mother’s Feathers,” why do the chicks gather around the feathers?', a: ['They think it’s their mother', 'They’re playing a game', 'There’s rice in them'], why: 'They are the mother hen’s feathers. The chicks don’t know she is gone.' },
  },
  {
    zh: { q: '白居易的诗：“劝君莫打枝头鸟，______。”', a: ['子在巢中望母归', '春风吹又生', '疑是地上霜'], why: '鸟妈妈的孩子，正在窝里等她回家。' },
    en: { q: 'Bai Juyi wrote: “Do not strike the bird on the branch: ______”', a: ['its young in the nest are waiting for their mother', 'the spring wind brings the grass back', 'I thought it was frost on the ground'], why: 'The mother bird’s chicks are in the nest, waiting for her to come home.' },
  },
  {
    zh: { q: '苏轼的诗：“为鼠常留饭，______。”', a: ['怜蛾不点灯', '低头思故乡', '处处闻啼鸟'], why: '可怜飞蛾扑火，苏轼夜里就不点灯。' },
    en: { q: 'Su Shi wrote: “Always leave some rice out for the mice; ______”', a: ['out of pity for the moths, leave the lamp unlit', 'I bow my head and think of home', 'everywhere I hear the birds singing'], why: 'So the moths would not fly into the flame, Su Shi left his lamp unlit.' },
  },
  {
    zh: { q: '飞蛾为什么会绕着灯飞？', a: ['灯光让它们分不清上下', '它们喜欢暖和', '灯上有好吃的'], why: '飞虫把背朝向最亮的地方来分清上下，灯光让它们迷了路。' },
    en: { q: 'Why do moths circle lamps?', a: ['The light confuses their sense of up and down', 'They like the warmth', 'There’s food on the lamp'], why: 'Flying insects turn their backs toward the brightest light to tell which way is up, so a lamp leads them astray.' },
  },
  {
    zh: { q: '下面哪种做法最能守护鱼儿？', a: ['让河水保持干净', '买外地的鱼放进河里', '把鱼捉回家养'], why: '守护它们本来的家，才是最好的护生。' },
    en: { q: 'Which of these does the most to protect fish?', a: ['Keeping rivers clean', 'Releasing fish bought from somewhere else', 'Taking fish home as pets'], why: 'Protecting the place they live is the best way to protect them.' },
  },
  {
    zh: { q: '丰子恺画的人物，常常有什么特点？', a: ['脸上没有五官', '都戴着帽子', '都在哈哈大笑'], why: '没有五官，看画的人反而能从动作里读出心情。' },
    en: { q: 'What is special about the people in Feng Zikai’s paintings?', a: ['Their faces often have no features', 'They all wear hats', 'They are all laughing'], why: 'Without faces, we read their feelings from how they stand and move.' },
  },
  {
    zh: { q: '李叔同写的哪首歌，至今还在传唱？', a: ['《送别》', '《茉莉花》', '《让我们荡起双桨》'], why: '“长亭外，古道边，芳草碧连天……”就是《送别》。' },
    en: { q: 'Which song by Li Shutong is still sung today?', a: ['“Farewell” (Songbie)', '“Jasmine Flower”', '“Let Us Row the Oars”'], why: '“Beyond the long pavilion, beside the ancient road…” is from “Farewell.”' },
  },
  {
    zh: { q: '地上有一只羽毛差不多长齐、会蹦会跳的小鸟，最好怎么做？', a: ['远远看着，别打扰它', '马上带回家', '把它放进鸟笼'], why: '它多半正在学飞，爸爸妈妈就在附近。' },
    en: { q: 'You find a young bird on the ground with most of its feathers, hopping about. What is best?', a: ['Watch from a distance and leave it alone', 'Take it home right away', 'Put it in a cage'], why: 'It is probably learning to fly, and its parents are close by.' },
  },
  {
    zh: { q: '在《生的扶持》里，两只螃蟹在做什么？', a: ['扶起跌倒的同伴', '打架', '抢食物'], why: '“一蟹失足，二蟹持扶。物知慈悲，人何不如。”' },
    en: { q: 'In “Helping Each Other Live,” what are the two crabs doing?', a: ['Helping a friend who fell', 'Fighting', 'Stealing food'], why: '“One crab loses its footing; two crabs hold it up.”' },
  },
  {
    zh: { q: '为什么不能随便把山里的画眉捉回家养？', a: ['它是受保护的野生动物', '画眉不会唱歌', '画眉太大了'], why: '画眉已被列为国家二级保护野生动物，它属于山林。' },
    en: { q: 'Why shouldn’t you catch a wild hwamei thrush to keep at home?', a: ['It is a protected wild species', 'Hwameis can’t sing', 'Hwameis are too big'], why: 'The hwamei is a protected species in China. It belongs in the woods.' },
  },
];
